//
//A second Playwright configuration, for taking the documentation's screenshots rather than for testing.
//
//Separate from playwright.config.js on purpose. These are not tests: they assert almost nothing and they
//write files into the repository, so folding them into e2e/ would put both in every run - a suite that is
//slower for no coverage, a spec count that moves when a picture changes, and images regenerated by anybody
//running the tests rather than by somebody who meant to.
//
//It shares the webServer, so `npm run screenshots` starts the app the same way the suite does.
//
const { defineConfig, devices } = require('@playwright/test');

module.exports = defineConfig({
    testDir: './screenshots',
    timeout: 180000,
    expect: { timeout: 20000 },

    //One at a time. They share a server and each one loads a file, switches views and waits for a render to
    //settle; in parallel they would race each other for the same tab-sized bottleneck and produce pictures
    //taken mid-draw, which is the one failure a screenshot cannot report.
    workers: 1,
    retries: 0,

    reporter: [['list']],
    use: {
        baseURL: 'http://localhost:5105',

        //The size the pictures are taken at. Wide enough that the toolbar does not wrap and the sidebars sit
        //beside the view rather than over it, which is how the app is meant to be seen.
        viewport: { width: 1400, height: 900 },
        deviceScaleFactor: 1
    },
    projects: [
        {
            name: 'chromium',
            use: { ...devices['Desktop Chrome'] }
        }
    ],
    webServer: {
        command: 'dotnet run --no-launch-profile --project GDSViewer.csproj --urls http://localhost:5105',

        //From the repository root, the same as playwright.config.js and for the same reason.
        cwd: require('path').join(__dirname, '..'),

        url: 'http://localhost:5105',
        timeout: 300000,
        reuseExistingServer: false
    }
});
