namespace GDSViewer.Tests;

///<summary>
///That everything `index.html` asks the browser for is actually there, spelled the way it asks.
///
///**A class of defect that cannot be seen on the machine it is written on.** Windows and macOS match a
///filename without regard to case, and every host worth deploying to matches it exactly - so a script tag
///that says `ThreeInterop.js` for a file named `threeInterOp.js` works all through development and 404s the
///moment it is published. Nothing else in the suite would notice: the C# tests do not read `index.html`, and
///the end-to-end suite runs against the dev server on the same case-insensitive disk.
///
///This is not hypothetical. The 3D interop's file was named `threeInterOp.js` on disk while `index.html`,
///the documentation and git's own index all said `ThreeInterop.js`. Only git had it right, which is the one
///reason a Linux clone still worked - so the app was one careless case-only rename away from shipping without
///a 3D view.
///
///Case is compared against the directory listing rather than with `File.Exists`, which is the whole point:
///`File.Exists` is exactly the check that cannot tell the difference here.
///</summary>
public class ShippedAssetTests
{
    ///<summary>
    ///Up out of the test binary to the repository root, the way <see cref="GdsTestData"/> finds the corpus.
    ///</summary>
    private static string Root()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);

        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "GDSViewer.sln")))
            directory = directory.Parent;

        Assert.NotNull(directory);

        return directory!.FullName;
    }

    private static string IndexHtml()
    {
        return Path.Combine(Root(), "wwwroot", "index.html");
    }

    ///<summary>
    ///Every local `src` and `href` in the page, as written. Absolute addresses and the framework's own
    ///`_framework` paths are left out - the first is somebody else's server and the second is generated by
    ///the build rather than committed.
    ///</summary>
    private static List<string> LocalAssetsAskedFor()
    {
        string html = File.ReadAllText(IndexHtml());

        var asked = new List<string>();

        foreach (var match in System.Text.RegularExpressions.Regex.Matches(html, @"(?:src|href)=""([^""]+)""").Cast<System.Text.RegularExpressions.Match>())
        {
            string target = match.Groups[1].Value;

            if (target.Length == 0 || target.StartsWith('#') || target.StartsWith("data:"))
                continue;

            if (target.Contains("://") || target.StartsWith("//"))
                continue;

            if (target.StartsWith("_framework/") || target.StartsWith("_content/"))
                continue;

            //Blazor's scoped-CSS bundle, written into the build output from the .razor.css files rather than
            //committed - so it is not under wwwroot to be found, and its name is the assembly's.
            if (target.EndsWith(".styles.css"))
                continue;

            //A cache-buster or a query is the server's business, not the file's.
            asked.Add(target.Split('?')[0].Split('#')[0].TrimStart('/'));
        }

        return asked;
    }

    [Fact]
    public void The_page_asks_for_something()
    {
        //Guards the regex rather than the app: a pattern that matched nothing would make every test below vacuous.
        var asked = LocalAssetsAskedFor();

        Assert.NotEmpty(asked);
        Assert.Contains("js/ThreeInterop.js", asked);
    }

    [Fact]
    public void Every_asset_the_page_asks_for_exists()
    {
        var missing = new List<string>();

        foreach (string asset in LocalAssetsAskedFor())
        {
            if (!File.Exists(Path.Combine(Root(), "wwwroot", asset.Replace('/', Path.DirectorySeparatorChar))))
                missing.Add(asset);
        }

        Assert.True(missing.Count == 0, $"index.html asks for files that are not under wwwroot:\n{string.Join("\n", missing)}");
    }

    ///
    ///And spelled the way the page asks, which is the half a case-insensitive disk hides.
    ///
    ///Compared against what the directory actually contains, because that is the only place the real spelling
    ///is recorded once `File.Exists` has agreed to ignore it.
    ///
    [Fact]
    public void Every_asset_is_spelled_the_way_the_page_asks()
    {
        var wrong = new List<string>();

        foreach (string asset in LocalAssetsAskedFor())
        {
            string full = Path.Combine(Root(), "wwwroot", asset.Replace('/', Path.DirectorySeparatorChar));

            string? folder = Path.GetDirectoryName(full);

            if (folder is null || !Directory.Exists(folder))
                continue;

            string wanted = Path.GetFileName(full);

            if (!Directory.EnumerateFiles(folder).Any(one => Path.GetFileName(one) == wanted))
                wrong.Add($"{asset} - the folder holds {string.Join(", ", Directory.EnumerateFiles(folder).Select(Path.GetFileName).Where(one => string.Equals(one, wanted, StringComparison.OrdinalIgnoreCase)))}");
        }

        Assert.True(wrong.Count == 0, $"index.html asks for a different spelling than the file on disk, which only fails once published:\n{string.Join("\n", wrong)}");
    }

    ///<summary>
    ///The same for the app's own interop, which the service worker also has to be able to cache: every file
    ///under `wwwroot/js` is one the page loads, so a file added there and never referenced is either dead or
    ///a script tag somebody forgot.
    ///</summary>
    [Fact]
    public void Every_interop_file_is_one_the_page_loads()
    {
        var asked = LocalAssetsAskedFor().ToHashSet();

        var unreferenced = Directory
            .EnumerateFiles(Path.Combine(Root(), "wwwroot", "js"), "*.js")
            .Select(Path.GetFileName)
            .Where(name => !asked.Contains($"js/{name}"))
            .ToList();

        Assert.True(unreferenced.Count == 0, $"Under wwwroot/js and loaded by nothing:\n{string.Join("\n", unreferenced)}");
    }
}
